development:
  adapter: mysql2
  database: bookmates_dev
  username: bookmates
  password: pass

test:
  adapter: mysql2
  database: bookmates_test
  username: bookmates
  password: pass

production:
  adapter: mysql2
  database: bookmates_prod
  username: bookmates
  password: pass
